name: Static-Web-App-Deploy

trigger: arthur

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    api_location: 'api'
    azure_static_web_apps_api_token: 7e422ea66c4de8b59f378f769daf9bd855d4acd0e089f9c1ddf41175640295582-82052ec3-6f62-414b-8fbf-6c14b6f0afa6010160251