name: Static-Web-App-Deploy

trigger: 
- arthur

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    api_location: 'api'
    azure_static_web_apps_api_token: 1b3839361ea5b495b4f4acfe4dcddb69dd27c08f2ab9386f1c253bae3f758cca2-a7740e26-5745-4755-97e4-85f9e359e055010160250